#ifndef __RCT6_PINMAP_H
#define __RCT6_PINMAP_H

#include "stm32f1xx_hal.h"

/*
 * RCT6 专用板引脚表，来源于原理图。
 * 后续各外设 BSP 只引用这里的定义，不再直接复制 F429 的引脚宏。
 */

/* 调试串口 USART1：PA9/PA10 */
#define RCT6_DEBUG_TX_PORT GPIOA
#define RCT6_DEBUG_TX_PIN  GPIO_PIN_9
#define RCT6_DEBUG_RX_PORT GPIOA
#define RCT6_DEBUG_RX_PIN  GPIO_PIN_10

/* RS485：USART2 默认引脚 PA2/PA3，PB8 为 DE/RE */
#define RCT6_RS485_TX_PORT GPIOA
#define RCT6_RS485_TX_PIN  GPIO_PIN_2
#define RCT6_RS485_RX_PORT GPIOA
#define RCT6_RS485_RX_PIN  GPIO_PIN_3
#define RCT6_RS485_DE_PORT GPIOB
#define RCT6_RS485_DE_PIN  GPIO_PIN_8

/* CAN1默认引脚：PA11=RX，PA12=TX。 */
#define RCT6_CAN_RX_PORT GPIOA
#define RCT6_CAN_RX_PIN  GPIO_PIN_11
#define RCT6_CAN_TX_PORT GPIOA
#define RCT6_CAN_TX_PIN  GPIO_PIN_12

/* W25Q256：SPI1，CS 使用 PA4，外部已有 10K 上拉 */
#define RCT6_FLASH_SPI      SPI1
#define RCT6_FLASH_SCK_PORT GPIOA
#define RCT6_FLASH_SCK_PIN  GPIO_PIN_5
#define RCT6_FLASH_MISO_PORT GPIOA
#define RCT6_FLASH_MISO_PIN  GPIO_PIN_6
#define RCT6_FLASH_MOSI_PORT GPIOA
#define RCT6_FLASH_MOSI_PIN  GPIO_PIN_7
#define RCT6_FLASH_CS_PORT  GPIOA
#define RCT6_FLASH_CS_PIN   GPIO_PIN_4

/* 两路 ADC：PC3=ADC1，PC4=ADC2 */
#define RCT6_ADC1_PORT     GPIOC
#define RCT6_ADC1_PIN      GPIO_PIN_3
#define RCT6_ADC1_CHANNEL  ADC_CHANNEL_13
#define RCT6_ADC2_PORT     GPIOC
#define RCT6_ADC2_PIN      GPIO_PIN_4
#define RCT6_ADC2_CHANNEL  ADC_CHANNEL_14

/* SDIO 4-bit：PC8~PC11 数据，PC12 时钟，PD2 命令 */
#define RCT6_SD_D0_PORT GPIOC
#define RCT6_SD_D0_PIN  GPIO_PIN_8
#define RCT6_SD_D1_PORT GPIOC
#define RCT6_SD_D1_PIN  GPIO_PIN_9
#define RCT6_SD_D2_PORT GPIOC
#define RCT6_SD_D2_PIN  GPIO_PIN_10
#define RCT6_SD_D3_PORT GPIOC
#define RCT6_SD_D3_PIN  GPIO_PIN_11
#define RCT6_SD_CK_PORT GPIOC
#define RCT6_SD_CK_PIN  GPIO_PIN_12
#define RCT6_SD_CMD_PORT GPIOD
#define RCT6_SD_CMD_PIN  GPIO_PIN_2

/* OLED I2C1：PB6/PB7 */
#define RCT6_OLED_SCL_PORT GPIOB
#define RCT6_OLED_SCL_PIN  GPIO_PIN_6
#define RCT6_OLED_SDA_PORT GPIOB
#define RCT6_OLED_SDA_PIN  GPIO_PIN_7

/* AT24C02C EEPROM 与 OLED 共用 I2C1，器件 7 位地址为 0x50。 */
#define RCT6_EEPROM_I2C       I2C1
#define RCT6_EEPROM_ADDRESS_7BIT 0x50U
#define RCT6_EEPROM_ADDRESS_HAL  (RCT6_EEPROM_ADDRESS_7BIT << 1)

/* 状态灯和两个软件按键 */
#define RCT6_LED_RED_PORT   GPIOB
#define RCT6_LED_RED_PIN    GPIO_PIN_10
#define RCT6_LED_GREEN_PORT GPIOB
#define RCT6_LED_GREEN_PIN  GPIO_PIN_11
#define RCT6_LED_ON_STATE   GPIO_PIN_RESET
#define RCT6_LED_OFF_STATE  GPIO_PIN_SET
#define RCT6_KEY1_PORT      GPIOA
#define RCT6_KEY1_PIN       GPIO_PIN_0
#define RCT6_KEY1_PRESSED_STATE GPIO_PIN_SET
#define RCT6_KEY2_PORT      GPIOC
#define RCT6_KEY2_PIN       GPIO_PIN_13
#define RCT6_KEY2_PRESSED_STATE GPIO_PIN_SET

/* 硬件复位 NRST 不属于 GPIO，由复位按键直接连接到 NRST。 */
#define RCT6_NRST_IS_HARDWARE_RESET 1U

/* RTC 低速晶振：PC14/PC15；SWD：PA13/PA14 */
#define RCT6_RTC_LSE_IN_PORT  GPIOC
#define RCT6_RTC_LSE_IN_PIN   GPIO_PIN_14
#define RCT6_RTC_LSE_OUT_PORT GPIOC
#define RCT6_RTC_LSE_OUT_PIN  GPIO_PIN_15

#endif /* __RCT6_PINMAP_H */
